language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install codecov"
# command to run test
script:
  - coverage run manage.py test
# command to run codecov
after_success:
  - codecov