# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerchat',
            name='chat_id',
            field=models.CharField(default='000000', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentchat',
            name='chat_id',
            field=models.CharField(default='000000', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
