# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20170109_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='units',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='units',
            field=models.ManyToManyField(to='timetable.Unit'),
        ),
    ]
