# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20170109_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentclass',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='studentclass',
            name='semester',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='day',
            field=models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')]),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='year',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')]),
        ),
    ]
