# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20170109_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='chat_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.IntegerField(choices=[(1, 'Theory'), (2, 'Practical')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='chat_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
