# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20170109_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclass',
            name='lessons',
            field=models.ManyToManyField(to='timetable.Lesson'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
