# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20170111_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='lessons',
            field=models.ManyToManyField(to='timetable.Lesson'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='units',
            field=models.ManyToManyField(to='timetable.Unit'),
        ),
    ]
