# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20170111_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='units',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='unit',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.Lecturer'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Theory'), (2, 'Practical')], default=1, null=True),
        ),
    ]
