# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_auto_20170113_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Period'),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='year',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh')]),
        ),
    ]
