# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_auto_20170125_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='chat_id',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, unique=True),
        ),
    ]
